/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as CConversationIdRouteImport } from './routes/c.$conversationId'
import { Route as ApiImageEditRouteImport } from './routes/api/image/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const CConversationIdRoute = CConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageEditRoute = ApiImageEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApiImageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/c/$conversationId': typeof CConversationIdRoute
  '/api/image/edit': typeof ApiImageEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/c/$conversationId': typeof CConversationIdRoute
  '/api/image/edit': typeof ApiImageEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/c/$conversationId': typeof CConversationIdRoute
  '/api/image/edit': typeof ApiImageEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/api/image'
    | '/c/$conversationId'
    | '/api/image/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/api/image'
    | '/c/$conversationId'
    | '/api/image/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/chat'
    | '/api/image'
    | '/c/$conversationId'
    | '/api/image/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRouteWithChildren
  CConversationIdRoute: typeof CConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$conversationId': {
      id: '/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof CConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/edit': {
      id: '/api/image/edit'
      path: '/edit'
      fullPath: '/api/image/edit'
      preLoaderRoute: typeof ApiImageEditRouteImport
      parentRoute: typeof ApiImageRoute
    }
  }
}

interface ApiImageRouteChildren {
  ApiImageEditRoute: typeof ApiImageEditRoute
}

const ApiImageRouteChildren: ApiImageRouteChildren = {
  ApiImageEditRoute: ApiImageEditRoute,
}

const ApiImageRouteWithChildren = ApiImageRoute._addFileChildren(
  ApiImageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRouteWithChildren,
  CConversationIdRoute: CConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
